In [ ]:
!pip install nltk
!pip install gensim
!pip install transformers
!pip install sentence-transformers
!pip install pyLDAvis
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 31.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 49.8 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.1 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=ae05984242b6947c4554aad468a5e3459ea7024835b051ee8

In [ ]:
!pip install contractions

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 10.8 MB/s eta 0:00:00


In [ ]:
!pip install -U pandas-profiling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.9/345.9 kB 26.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 58.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.8/33.8 MB 35.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 12.1 MB/s eta 0:00:00
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.10.1
    Uninstalling scipy-1.10.1:
      Successfully uninstalled scipy-1.10.1
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.7.1
    Uninstalling matplotlib-3.7.1

In [ ]:
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import wordcloud
import nltk
import unicodedata
import contractions
import pickle
import urllib.request
import requests
import spacy
import json
%matplotlib inline

from bs4 import BeautifulSoup
from bs4.element import Comment
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
from collections import defaultdict
from contractions import contractions_dict
from wordcloud import WordCloud, STOPWORDS
from transformers import pipeline

from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem.porter import PorterStemmer
from sentence_transformers import SentenceTransformer, util
from gensim.corpora import Dictionary
from gensim.models.ldamodel import LdaModel
from spacy import displacy

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('universal_tagset')
nltk.download('wordnet')
nltk.download('punkt')

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from contractions import contractions_dict
from scipy import stats
from scipy import sparse

import pyLDAvis

# Visualize the topics
pyLDAvis.enable_notebook()

tokenizer = ToktokTokenizer()
stopword_list = nltk.corpus.stopwords.words('english')
scaler = MinMaxScaler()
std_scaler = StandardScaler()
stops = set(stopword_list)
stemmer = nltk.stem.SnowballStemmer('english')
wordlemmatizer = WordNetLemmatizer()
tokenizer = nltk.word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


**NLP Data. Pick 2 poets, scrape 10 poems each . Put them in a json datastructure and save it under the poets name, in your team drive under folder 'DataSets'**

**Get Scraped Data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
     

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Mounted at /content/drive


In [ ]:
df_john = pd.read_csv('/content/drive/MyDrive/NLP_ML/john_keats.csv')

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_john.drop(columns='Unnamed: 0', inplace=True)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_john.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Title           10 non-null     object
 1   Poem            10 non-null     object
 2   Poem_for_Human  10 non-null     object
dtypes: object(3)
memory usage: 368.0+ bytes


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_john.head()

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Title  \
0                        “Fancy”   
1  “Ode on a Grecian Urn” (1819)   
2         “To Lord Byron” (1814)   
3     “La Belle Dame Sans Merci”   
4              Ode on Melancholy   

                                                Poem  \
0  \nPleasure never is at home:At a touch sweet P...   
1  Heard melodies are sweet, but those unheardAre...   
2  Byron! how sweetly sad thy melody! Attuning st...   
3  O what can ail thee, knight-at-arms,Alone and ...   
4  No, no, go not to Lethe, neither twistWolf’s-b...   

                                      Poem_for_Human  
0  Ever let the Fancy roam,\nPleasure never is at...  
1  Heard melodies are sweet, but those unheard\nA...  
2  Byron! how sweetly sad thy melody!\nAttuning s...  
3  O what can ail thee, knight-at-arms,Alone and ...  
4  No, no, go not to Lethe, neither twistWolf’s-b...

In [ ]:
df_alfred = pd.read_csv('/content/drive/MyDrive/NLP_ML/alfred_tennyson.csv')

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_alfred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      10 non-null     int64 
 1   Title           10 non-null     object
 2   Poem            10 non-null     object
 3   Poem_for_Human  9 non-null      object
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_alfred.head()

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Unnamed: 0                        Title  \
0           0                The BlackBird   
1           1  The Deadth Of The Old Year    
2           2                I Entreat You   
3           3            Crossing The Bar    
4           4                    The Brook   

                                                Poem  \
0  The espaliers and the standards all Are thine;...   
1  For the old year lies a-dying.Old year you mus...   
2                Good, but better when you share it.   
3  Sunset and evening star,And one clear call for...   
4  I come from haunts of coot and hern,I make a s...   

                                      Poem_for_Human  
0  O blackbird! sing me something well:\nWhile al...  
1  Full knee-deep lies the winter snow,\nAnd the ...  
2  I entreat you, Alfred Tennyson,\nCome and shar...  
3  Sunset and evening star,And one clear call for...  
4  I come from haunts of coot and hern,I make a s...

**JSON Conversion**

In [ ]:
result_john = df_john.to_json(orient="index")
parsed = json.loads(result_john)
json.dumps(parsed, indent=4)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


'{\n    "0": {\n        "Title": "\\u201cFancy\\u201d",\n        "Poem": "\\nPleasure never is at home:At a touch sweet Pleasure melteth,Like to bubbles when rain pelteth;Then let winged Fancy wanderThrough the thought still spread beyond her:Open wide the mind\\u2019s cage-door,She\\u2019ll dart forth, and cloudward soar.",\n        "Poem_for_Human": "Ever let the Fancy roam,\\nPleasure never is at home:\\nAt a touch sweet Pleasure melteth,\\nLike to bubbles when rain pelteth;\\nThen let winged Fancy wander\\nThrough the thought still spread beyond her:\\nOpen wide the mind\\u2019s cage-door,\\nShe\\u2019ll dart forth, and cloudward soar.\\nO sweet Fancy! let her loose;\\nSummer\\u2019s joys are spoilt by use,\\nAnd the enjoying of the Spring\\nFades as does its blossoming;\\nAutumn\\u2019s red-lipp\\u2019d fruitage too,\\nBlushing through the mist and dew,\\nCloys with tasting: What do then?\\nSit thee by the ingle, when\\nThe sear faggot blazes bright,\\nSpirit of a winter\\u2019s n

In [ ]:
with open('/content/drive/MyDrive/NLP_ML/john_keats.txt', 'w') as outfile:
    json.dump(result_john, outfile)
     

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
result_alfred = df_alfred.to_json(orient="index")
parsed_alfred = json.loads(result_alfred)
json.dumps(parsed_alfred, indent=4)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


'{\n    "0": {\n        "Unnamed: 0": 0,\n        "Title": "The BlackBird",\n        "Poem": "The espaliers and the standards all Are thine; the range of lawn and park:The unnetted black-hearts ripen dark,All thine, against the garden wall.",\n        "Poem_for_Human": "O blackbird! sing me something well:\\nWhile all the neighbours shoot thee round,\\nI keep smooth plats of fruitful ground,\\nWhere thou may\'st warble, eat and dwell.\\n\\nThe espaliers and the standards all\\nAre thine; the range of lawn and park:\\nThe unnetted black-hearts ripen dark,\\nAll thine, against the garden wall.\\n\\nYet, tho\' I spared thee all the spring,\\nThy sole delight is, sitting still,\\nWith that gold dagger of thy bill\\nTo fret the summer jenneting.\\n"\n    },\n    "1": {\n        "Unnamed: 0": 1,\n        "Title": "The Deadth Of The Old Year ",\n        "Poem": "For the old year lies a-dying.Old year you must not die;You came to us so readily,You lived with us so steadily, Old year you shall 

In [ ]:
with open('/content/drive/MyDrive/NLP_ML/alfred_tennyson.txt', 'w') as outfile:
    json.dump(result_alfred, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
parsed_alfred["0"]

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'Unnamed: 0': 0,
 'Title': 'The BlackBird',
 'Poem': 'The espaliers and the standards all Are thine; the range of lawn and park:The unnetted black-hearts ripen dark,All thine, against the garden wall.',
 'Poem_for_Human': "O blackbird! sing me something well:\nWhile all the neighbours shoot thee round,\nI keep smooth plats of fruitful ground,\nWhere thou may'st warble, eat and dwell.\n\nThe espaliers and the standards all\nAre thine; the range of lawn and park:\nThe unnetted black-hearts ripen dark,\nAll thine, against the garden wall.\n\nYet, tho' I spared thee all the spring,\nThy sole delight is, sitting still,\nWith that gold dagger of thy bill\nTo fret the summer jenneting.\n"}

**Build JSON Structure**

In [ ]:
john_keats = {

}

alfred_tennyson = {

}

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


**Data Cleaning**

In [ ]:
def cleanPoemText(text):
    

    text = contractions.fix(text)
    
    text = text.strip().lower()
    
    text = re.sub(r"'", ' ', text)
    
    filters='!"\'#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n'
    translate_dict = dict((i, " ") for i in filters)
    translate_map = str.maketrans(translate_dict)
    text = text.translate(translate_map)

    text = ' '.join([w for w in text.split()])

    # Replace multiple space with one space
    text = re.sub(' +', ' ', text)
    
    text = ''.join(text)

    return text

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<>:10: DeprecationWarning: invalid escape sequence \]
<>:10: DeprecationWarning: invalid escape sequence \]
<ipython-input-19-ace87d021779>:10: DeprecationWarning: invalid escape sequence \]
  filters='!"\'#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n'


**Clean Poem Text**

In [ ]:
embedding = ''
def buildPoemArray(poet, data):
  poems = []
  for i in data:
    poem = data[i]["Poem"]

    clean_poem = cleanPoemText(poem)
    idx = "poem" + str(i)
    poet[idx] = clean_poem
    poems.append(idx)
  poet['poems_array'] = poems

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
buildPoemArray(alfred_tennyson, parsed_alfred)
buildPoemArray(john_keats, parsed)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
alfred_tennyson

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:

john_keats

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
john_keats_poems = john_keats.copy()
alfred_tennyson_poems = alfred_tennyson.copy()

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


**Run Part-Of-Speech, extract verbs, nouns and adjectives**

In [ ]:
def getPOS(poet):
  global_vrb= set()
  global_nns= set()
  global_adj= set()
  for key in poet['poems_array']:
    text = poet[key]
    wrd_list = word_tokenize(text)
    pos_val = nltk.pos_tag(wrd_list)
    poet["pos_"+key] = pos_val

    vrb = set([word for (word, pos) in pos_val if (pos.startswith('VB'))])
    nns = set([word for (word, pos) in pos_val if (pos.startswith('NN'))])
    adj = set([word for (word, pos) in pos_val if (pos.startswith('JJ'))])

    poet["verbs_"+key] = list(vrb)
    poet["adjectives_"+key] = list(adj)
    poet["nouns_"+key] = list(nns)

    global_vrb = set.union(global_vrb, vrb)
    global_nns = set.union(global_nns, nns)
    global_adj = set.union(global_adj, adj)

  poet['all_verbs'] = list(global_vrb)
  poet['all_nouns'] = list(global_nns)
  poet['all_adjectives'] = list(global_adj)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
alfred_tennyson_pos = alfred_tennyson.copy()
getPOS(alfred_tennyson_pos)
alfred_tennyson_pos

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
alfred_tennyson

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
john_keats_pos = john_keats.copy()
getPOS(john_keats_pos)
john_keats_pos

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
john_keats

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

**Store the POS JSON Data to File**

In [ ]:
with open('/content/drive/MyDrive/NLP_ML/john_keats.json', 'w') as outfile:
    json.dump(john_keats_pos, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
with open('/content/drive/MyDrive/NLP_ML/alfred_tennyson.json', 'w') as outfile:
    json.dump(alfred_tennyson_pos, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


**Summarization using transformers**

In [ ]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
summarizer = pipeline("summarization", model="t5-base", tokenizer="t5-base", framework="tf")

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


/usr/local/lib/python3.9/dist-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


In [ ]:
def getSummaryOfPoem(poet):
  def removeQuotes(mydata):
    new_data = mydata.strip('“”')
    return new_data
  count = 0
  for key in poet['poems_array']:
    count += 1;
    text = poet[key] 
    text = removeQuotes(text)
    summary_text = summarizer(text, max_length=512, min_length=5, do_sample=False)[0]['summary_text']
    poet["summary_"+key] = summary_text
  
  return poet

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
from time import gmtime, strftime
print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))

from time import gmtime, strftime
print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))

import timeit

start = timeit.default_timer()

2023-04-11 01:05:07
2023-04-11 01:05:07


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
john_keats_sum = john_keats.copy()
alfred_tennyson_sum = alfred_tennyson.copy()
data_john_keats = getSummaryOfPoem(john_keats_sum)
data_alfred_tennyson = getSummaryOfPoem(alfred_tennyson_sum)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
Your max_length is set to 512, but you input_length is only 58. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=29)
/usr/local/lib/python3.9/dist-packages/transformers/generation/tf_utils.py:745: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Your max_length is set to 512, but you input_length is only 48. You might consider decrea

In [ ]:
#Your statements here

stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  709.6815052489999


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
data_alfred_tennyson

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
alfred_tennyson_sum

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
john_keats_sum

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

**Store the summarized JSON Data to File**

In [ ]:
with open('/content/drive/MyDrive/NLP_ML/john_keats.json', 'w') as outfile:
    json.dump(john_keats_sum, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
with open('/content/drive/MyDrive/NLP_ML/alfred_tennyson.json', 'w') as outfile:
    json.dump(alfred_tennyson_sum, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


**Interchange the Verbs and Adjectives for both the poets using transformer**


In [ ]:
model = SentenceTransformer('stsb-roberta-large')


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
def getSemanticSimilarity(p1,p2):
  embedding1 = model.encode(p1, convert_to_tensor=True)
  embedding2 = model.encode(p2, convert_to_tensor=True)
  cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
  print(cosine_scores) 
  similarity_score = cosine_scores.item()
  return similarity_score

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
getSemanticSimilarity(john_keats_pos['all_verbs'][0],alfred_tennyson_pos["all_verbs"][0])


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


tensor([[0.0468]])


0.04682961478829384

**Swapping the Verbs based on similarity score**

In [ ]:
def swapVerbs(p1,p2,text):
    for v1 in p1:
      for v2 in p2:
        score = getSemanticSimilarity(v1,v2)
        if score > 0.3:
          text = text.replace(v1,v2)
          print("verb")
          print(text)
          break
    return text

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


 Swapping the Adjectives based on similarity score


In [ ]:
def swapAdjectives(p1,p2, poem):
  text = poem
  for a1 in p1:
    for a2 in p2:
      print("inside loop 2")
      print(a1)
      print(a2)
      print(text)
      score = getSemanticSimilarity(a1,a2)
      if score > 0.3:
        text = text.replace(a1,a2)
        print("adjective")
        print(text)
  return text

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
def swapIteration(poet1, poet2, text):
    p2_verbs = poet2["all_verbs"]
    p1_verbs = poet1["all_verbs"]
    p2_verbs = p2_verbs[0:2]
    p1_verbs = p1_verbs[0:2]
    print(p1_verbs)
    print(p2_verbs)
    new_text = swapVerbs(p1_verbs, p2_verbs, text)
    print("new text verbs")
    print(new_text)
    # print(text)
    p2_adjectives = poet2["all_adjectives"]
    p1_adjectives = poet1["all_adjectives"]
    p2_adjectives = p2_adjectives[0:2]
    p1_adjectives = p1_adjectives[0:2]
    brand_new_text = swapAdjectives(p1_adjectives, p2_adjectives, new_text)
    print("new text adjectives")
    print(brand_new_text)
    return brand_new_text

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


**John Poems Swapped Verbs and Adjectives of Alfred Tennyson Poems**

In [ ]:
john_keats_poems_2 = john_keats_poems.copy()
john_keats_poems_2.pop('poems_array')
john_keats_poems_swapped=[]
for i in john_keats_poems:
  print("poems:")
  print(i)
  # inx = 'poem'+str(i);
  poem_str = str(john_keats_poems[i]);
  print(poem_str)

  john_keats_poems_swapped.append(swapIteration(john_keats_pos, alfred_tennyson_pos, poem_str))

poems:
poem0
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar
['byron', 'delved']
['sleeping', 'sea']


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


tensor([[0.0468]])
tensor([[0.1364]])
tensor([[0.1811]])
tensor([[0.1595]])
new text verbs
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar
inside loop 2
fancy
orient
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar
tensor([[0.2333]])
inside loop 2
fancy
white
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar
tensor([[0.2143]])
inside loop 2
soothest
orient
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when

**Printing the new poems after swapping**

In [ ]:
john_keats_poems_swapped


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


['pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy pale forehead to be kiss’d by nightshade rub

**TODO: We need to format the poem in a human readable manner**

In [ ]:
alfred_tennyson_poems_swapped = []
alfred_tennyson_poems_2 = alfred_tennyson_poems.copy()
alfred_tennyson_poems_2.pop('poems_array')
for i in alfred_tennyson_poems:
  print("poems:")
  print(i)
  # inx = 'poem'+str(i);
  poem_str_2 = str(alfred_tennyson_poems[i]);
  print(poem_str_2)

  alfred_tennyson_poems_swapped.append(swapIteration(john_keats_pos, alfred_tennyson_pos, poem_str_2))

poems:
poem0
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
['byron', 'delved']
['sleeping', 'sea']


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


tensor([[0.0468]])
tensor([[0.1364]])
tensor([[0.1811]])
tensor([[0.1595]])
new text verbs
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
inside loop 2
fancy
orient
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
tensor([[0.2333]])
inside loop 2
fancy
white
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
tensor([[0.2143]])
inside loop 2
soothest
orient
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
tensor([[0.2846]])
inside loop 2
soothest
white
the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall
tensor([[0.0190]])
n

**Printing the new poems after swapping**

In [ ]:
alfred_tennyson_poems_swapped

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


['the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'good but better when you share it',
 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river winding clearly',
 'then might thy rays pass thro to the other side so swift

**Swapped Poem**

In [ ]:
def buildSwappedPoemArray(poet,data):
  poems = []
  data_length = len(data)
  for i in range(data_length):
    poem = data[i]
    #clean_poem = cleanPoemText(poem)
    idx = "poem" + str(i)
    poet[idx] = poem
    poems.append(idx)
  poet['poems_swapped_array'] = poems

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
john_keats_swapped = {

}

alfred_tennyson_swapped = {

}


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
john_keats_poems_swapped

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


['pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy pale forehead to be kiss’d by nightshade rub

In [ ]:
buildSwappedPoemArray(john_keats_swapped,john_keats_poems_swapped)
buildSwappedPoemArray(alfred_tennyson_swapped,alfred_tennyson_poems_swapped)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
john_keats_swapped

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
john_keats_swapped_to_json_file = john_keats_swapped.copy()
john_keats_swapped_to_json_file.pop('poems_swapped_array')
john_keats_swapped_to_json_file.pop('poem10')

alfred_tennyson_swapped_to_json_file = alfred_tennyson_swapped.copy()
alfred_tennyson_swapped_to_json_file.pop('poems_swapped_array')
alfred_tennyson_swapped_to_json_file.pop('poem10')

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


"['poem0', 'poem1', 'poem2', 'poem3', 'poem4', 'poem5', 'poem6', 'poem7', 'poem8', 'poem9']"

In [ ]:
john_keats_swapped_to_json_file

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
alfred_tennyson_swapped_to_json_file

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
with open('/content/drive/MyDrive/NLP_ML/afterswap_john_keats.json', 'w') as outfile:
    json.dump(john_keats_swapped_to_json_file, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
with open('/content/drive/MyDrive/NLP_ML/alfred_tennysonafterswap.json', 'w') as outfile:
    json.dump(alfred_tennyson_swapped_to_json_file, outfile)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
import re
import numpy as np
import pandas as pd
from pprint import pprint

# Gensim
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel

# spacy for lemmatization
import spacy

# Plotting tools
import pyLDAvis
import matplotlib.pyplot as plt
%matplotlib inline

# Enable logging for gensim - optional
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.ERROR)

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
john_keats_choherence_input = john_keats.copy()
john_keats_choherence_input.pop('poems_array')
john_keats_choherence_input

{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
swapped_john_keats_choherence_input = john_keats_swapped.copy()
swapped_john_keats_choherence_input.pop('poems_swapped_array')
swapped_john_keats_choherence_input

{'poem0': 'pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar',
 'poem1': 'heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone',
 'poem2': 'byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die',
 'poem3': 'o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done',
 'poem4': 'no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy

In [ ]:
coherence_perplexity_calculator = alfred_tennyson.copy()
coherence_perplexity_calculator.pop('poems_array')
coherence_perplexity_calculator

{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
swapped_coherence_perplexity_calculator = alfred_tennyson_swapped.copy()
swapped_coherence_perplexity_calculator.pop('poems_swapped_array')
swapped_coherence_perplexity_calculator

{'poem0': 'the espaliers and the standards all are thine the range of lawn and park the unnetted black hearts ripen dark all thine against the garden wall',
 'poem1': 'for the old year lies a dying old year you must not die you came to us so readily you lived with us so steadily old year you shall not die',
 'poem2': 'good but better when you share it',
 'poem3': 'sunset and evening star and one clear call for me and may there be no moaning of the bar when i put out to sea',
 'poem4': 'i come from haunts of coot and hern i make a sudden sallyand sparkle out among the fern to bicker down a valley',
 'poem5': 'come not as thou camest of late flinging the gloom of yesternight on the white day but robed in soften’d light of orient state',
 'poem6': 'her open eyes desire the truth the wisdom of a thousand years is in them may perpetual youth keep dry their light from tears',
 'poem7': 'only reapers reaping early in among the bearded barley hear a song that echoes cheerly from the river wind

In [ ]:
!pip install -upgrade gensim


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -u


In [ ]:
!pip install pyLDAvis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
poem_count = len(john_keats_choherence_input)
john_poem_list=[]
for j in john_keats_choherence_input:
  poem_index =  str(j)
  print(poem_index)
  print(john_keats_choherence_input[poem_index])
  john_poem_list.append(john_keats_choherence_input[poem_index])
print(john_poem_list)

poem0
pleasure never is at home at a touch sweet pleasure melteth like to bubbles when rain pelteth then let winged fancy wanderthrough the thought still spread beyond her open wide the mind’s cage door she will dart forth and cloudward soar
poem1
heard melodies are sweet but those unheardare sweeter therefore ye soft pipes play on not to the sensual ear but more endear’d pipe to the spirit ditties of no tone
poem2
byron how sweetly sad thy melody attuning still the soul to tenderness as if soft pity with unusual stress had touch’d her plaintive lute and thou being by hadst caught the tones nor suffer’d them to die
poem3
o what can ail thee knight at arms alone and palely loitering the sedge has withered from the lake and no birds sing o what can ail thee knight at arms so haggard and so woe begone the squirrel’s granary is full and the harvest’s done
poem4
no no go not to lethe neither twistwolf’s bane tight rooted for its poisonous wine nor suffer thy pale forehead to be kiss’d by ni

**Original John Keats Poem's perplexity and coherence score**

In [ ]:
!pip install attrs==19.1.0
     

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Attempting uninstall: attrs
    Found existing installation: attrs 22.2.0
    Uninstalling attrs-22.2.0:
      Successfully uninstalled attrs-22.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
visions 0.7.5 requires attrs>=19.3.0, but you have attrs 19.1.0 which is incompatible.
pytest 7.2.2 requires attrs>=19.2.0, but you have attrs 19.1.0 which is incompatible.


In [ ]:
!pip install pandas --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 52.2 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.4
    Uninstalling pandas-1.4.4:
      Successfully uninstalled pandas-1.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.1.2 requires pandas!=1.4.0,<1.6,>1.1, but you have pandas 2.0.0 which is incompatible.
visions 0.7.5 requires attrs>=19.3.0, but you have attrs 19.1.0 which is incompatible.
